### ISSUE TITLE
Debugging with chrome://inspect ?

### ISSUE THREAD

**Issue by abcd-ca** [pklaschka/xd-plugin-boilerplate#48]
Hi,

Did you ever have chrome debugging working with this boilerplate?

Prior to adding webpack I tried debugging my plugin with chrome://inspect and it was working using a debug.json containing,

```
{
  "port": 9345,
  "breakOnStart": true
}
```

Then I added my own webpack setup and it worked great but I lost chrome debugging. I tried your plugin and debugging in chrome still wasn't available. No targets appear under the "Remote Target #LOCALHOST" header.

I've tried playing with webpack's devtool values but it's not helping.

**Comment by pklaschka** [comment]
Since you've asked this in two different places, I'll go ahead and move this discussion to https://forums.adobexdplatform.com/t/cant-debug-in-chrome-devtools-only-when-using-webpack/1798 🙂 .

**Comment by pklaschka** [comment]
For reference:
Using the Chrome Developer process inside XD works with the `xd-plugin-boilerplate`, too. The `debug.json` has to be at `/dist/debug.json`. Other than that, it works like for any other plugin (right now, XD's docs for that are slightly outdated, cf. https://forums.adobexdplatform.com/t/cant-debug-in-chrome-devtools-only-when-using-webpack/1798/2 and the references there), but other than that, this boilerplate doesn't hinder using the debugging tools 🙂 ...
